name: Repo Sync

on:
  schedule:
    - cron:  '0 7 * * *'  # This will run the workflow daily at 7 AM UTC
  workflow_dispatch:     # This allows to manually trigger the workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0  # this is required to fetch all branches and tags

    - name: Fetch Upstream
      run: |
        git remote add upstream ${{ secrets.SOURCE_REPO }}
        git fetch upstream
        git fetch upstream --tags

    - name: Merge changes
      run: |
        git merge upstream/master

    - name: Push Tags
      run: |
        git push origin --tags
